### ISSUE TITLE
Android service

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-droid#12]
Register foreground service with persistent notification to allow sender and receiver to run even if the app is closed. We would also need a button in the notification that stops and terminates the service.

See also #1, the implementation of these issues might overlap.

**Comment by BelchingJalapeno** [comment]
I'd like to work on this. There should be a separate notification for both the sender and receiver if they are both running at the same time, is that correct?

**Comment by gavv** [comment]
@BelchingJalapeno You're welcome! I think a single notification for the whole app would be more convenient. Sender and receiver threads could both belong to the same service with a single notification.

**Comment by gavv** [comment]
Merged!
