### ISSUE TITLE
Please take care for versioning

### ISSUE THREAD

**Issue by IzzySoft** [roc-streaming/roc-droid#24]
Thanks for making the APK available for everyone here! Checking it I noticed its versioning doesn't match the tag name. Could you please keep an eye on this?

* make `versionName` reflect the (human readable) version, i.e. what you expect people report along with issues
* make sure to always increase `versionCode` with each new release, as that's what Android uses to keep versions apart (it only considers higher versionCodes to represent updates)

Thanks!

**Comment by gavv** [comment]
Thanks for report.

Here is related gradle code that I use in another project:

```groovy
def getVersionString = { ->
    def stdout = new ByteArrayOutputStream()
    exec {
        commandLine "git", "describe", "--tags", "--abbrev=0"
        standardOutput = stdout
    }
    return stdout.toString().trim().replaceAll("v", "")
}

def computeVersionCode = { verStr ->
    def verCode = 0
    def mult = 1
    verStr.tokenize(".").reverse().each {
        verCode += it.toInteger() * mult
        mult *= 1000
    }
    return verCode
}

android {
    ...

    defaultConfig {
       ...

        manifestPlaceholders = [
            VERSION_CODE: computeVersionCode(getVersionString()),
            VERSION_NAME: getVersionString(),
```

And in AndroidManifest.xml:

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="..."
    android:versionCode="${VERSION_CODE}"
    android:versionName="${VERSION_NAME}">
```

**Comment by IzzySoft** [comment]
Thanks for picking this up!

Not being an Android dev I cannot completely follow. But wouldn't the former mean that `versionName` is calculated by tag name and thus only available after tagging? That in conjunction with the dynamic version (variable place-holder) in Maniffest/`build.gradle` would e.g. make auto-updates at F-Droid.org impossible (that would need static values in `build.gradle`/Manifest the updater would look for at tag level, especially comparing whether the lastest `versionCode` was already built before).

It would however work with my repo (where your app is [currently listed](https://apt.izzysoft.de/fdroid/index/apk/org.rocstreaming.rocdroid)) as it makes sure tag name and `versionName` match. So if you enable that here (or have the two matching by other means), please give me a ping so I can adjust the config for my updater accordingly.

**Comment by gavv** [comment]
> But wouldn't the former mean that versionName is calculated by tag name and thus only available after tagging?

Yep, like you make git tag, then run build, then you get apk with correct manifest with versions.

Do I get it, F-Droid gets version from source code and can't handle when placeholders are used for version? I'd expect that the version should come from apk instead. Am I wrong?

**Comment by IzzySoft** [comment]
> Yep, like you make git tag, then run build, then you get apk with correct manifest with versions.

Then for some reason you need to build a previous release, and… hm. Well, I'd not like it that way – but it's not my project so I won't complain as long as my updater can deal with the results. And my updater doesn't look "backwards" :see_no_evil:

> I'd expect that the version should come from apk instead. Am I wrong?

Yes, you are wrong – in this case. Because, where does the APK come from? F-Droid builds it from source. So we'd have the chicken-and-egg issue. One of the reasons I bring this up here: should you want to have your app on F-Droid.org one day, your current approach would not work with that. You cannot expect F-Droid adjusting their updater for such special configurations only featured by a single repo, too much overhead (plus the code would soon become unmaintainable).

**Comment by gavv** [comment]
> Then for some reason you need to build a previous release, and… hm.

It should not be a problem I think. When you checkout previous release, `git describe --tags --abbrev=0` will report different tag, the one you checked out.

> Yes, you are wrong – in this case. Because, where does the APK come from? F-Droid builds it from source. So we'd have the chicken-and-egg issue. One of the reasons I bring this up here: should you want to have your app on F-Droid.org one day, your current approach would not work with that. You cannot expect F-Droid adjusting their updater for such special configurations only featured by a single repo, too much overhead (plus the code would soon become unmaintainable).

Oh I see.

So, just to be sure: F-Droid downloads the source code, and *before building* it, it finds AndroidManifest.xml in the source code, and it expects that it will have hardcoded version name and code, right?

I think supporting F-Droid is a good idea, if it works like this, we should adjust code to it.

Then we could go this way:

* hardcode version name and code in AndroidManifest.xml
* on CI, when we're building a tag, check that the tag matches value from AndroidManifest.xml, and refuse to build if it doesn't match

@ortex what do you think?

**Comment by IzzySoft** [comment]
> will report different tag

Ah, TIL – didn't know that it applies to the commit currently checked out, thanks!

> F-Droid downloads the source code, and *before building* it, it finds AndroidManifest.xml

Pretty close. If I'm not mistaken, CheckUpdates just pulls the relevant files (`build.gradle`, `AndroidManifest.xml`) from the latest tag (corresponding to the definition in the apps' `*.yml`) to check if the `versionCode` is higher than the latest build already available at F-Droid – and if so, adds the corresponding build block. Later, the build server sees that (new) build block, cannot find a corresponding APK, and thus builds it.

That is how I understand it, and I'm no dev – so it's just a rough description of the process and the [details need to be verified](https://gitlab.com/fdroid/fdroidserver/-/blob/master/fdroidserver/checkupdates.py) before taking my word on it :wink:

> I think supporting F-Droid is a good idea, if it works like this, we should adjust code to it.

Wonderful! :smiley:

> hardcode version name and code in AndroidManifest.xml

That should be supported, yes. If it does not matter to you, AFAIK [`build.gradle`](https://github.com/roc-streaming/roc-droid/blob/main/app/build.gradle#L14) would be the better place (and be looked for first).

**Comment by gavv** [comment]
@IzzySoft Thanks for explanations.

Just merged #35, AndroidManifest now have hardcoded version name and code for 0.0.3. Let us know if this works for you and whether you need to tag a new release.

**Comment by IzzySoft** [comment]
Thanks! For my updater I can tell when the next release has been made, but am confident it will work out (expecting to find something like `0.0.4+4` at a `v0.0.4` tag). It will need a one-time manual update then (as my updater currently would look for something greater than `1.0`), so please give me a ping when it's there (I'd suggest leaving this issue open until then and I'll close it when confirming after the ping).

**Comment by gavv** [comment]
@ortex maybe you could tag a release?

**Comment by IzzySoft** [comment]
Thanks! Pulled manually, ran a check afterwards: looks good on my end. If you keep up versioning, new releases should be detected automatically and users will get their update notification.

**Comment by gavv** [comment]
Awesome, thanks!

**Comment by gavv** [comment]
@IzzySoft let I guess we can close this?

**Comment by IzzySoft** [comment]
I'd say so. We can reopen if we both were assuming wrongly here :see_no_evil:
