### ISSUE TITLE
Publish release version of APK on github

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-droid#39]
~~Currently APK is building with debugging enabled.~~

We need to sign release apk (probably with https://github.com/marketplace/actions/sign-android-release) and attach release apk to github release instead of debug apk.

**Comment by tushartripathi** [comment]
Would like to contribute.

**Comment by tushartripathi** [comment]
![alt text](https://i.imgur.com/r2A9VN2.png)

Got this result in my forked repo. Permission was denied due to forked repo
