### ISSUE TITLE
UI get's cut in landscape mode

### ISSUE THREAD

**Issue by gurtonbuster** [roc-streaming/roc-droid#44]
![Screenshot_20230126-153229573 (1)](https://user-images.githubusercontent.com/44816323/214809080-9869b51f-f01b-4a45-963f-b5d0fc2b8a96.jpg)

The Sender section is cut off as seen in the screenshot above making it impossible to change the IP or to start the sender in landscape mode.

**Comment by gavv** [comment]
Hi! I think this will be fixed by https://github.com/roc-streaming/roc-droid/pull/42

**Comment by gavv** [comment]
Just checked, scroll bars now appear when necessary. @ortex will close this issue after a release is tagged.

However there are still some things to be improved, I created a new issue for that: https://github.com/roc-streaming/roc-droid/issues/52

**Comment by ortex** [comment]
fixes released https://github.com/roc-streaming/roc-droid/releases/tag/v0.0.5
