### ISSUE TITLE
Add licenses page

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-droid#51]
Add a page that displays list of all dependencies and their licenses (including transitive ones).

Java dependencies can be gathered from gradle (I believe there should be gradle plugins for that). Information about roc license and dependencies can be found here:

* https://roc-streaming.org/toolkit/docs/building/dependencies.html
* https://roc-streaming.org/toolkit/docs/about_project/licensing.html

**Comment by PranatPraveer** [comment]
From where the page should open in app ?
And do i need to create a new fragment?

**Comment by gavv** [comment]
Hi,

> From where the page should open in app ?

From "About" page, I guess.

**Comment by githubashutoshsoni** [comment]
Can we do this as a webview?

**Comment by githubashutoshsoni** [comment]
Can you please assign this to me? @gavv

**Comment by gavv** [comment]
I think webview with toolkit dependencies is not a good idea.

On one hand, we anyway should show many dependencies that are not listed there, and are specific to roc-java or roc-droid, but not roc-toolkit (I think you can somehow l8st them using gradle).

On the other hand, many dependencies of toolkit are not relevant to roc-droid, e.g. build time and developer dependencies. So we actually need to show only a few dependencies from toolkit docs.

I think we could use gradle for java dependencies and just add a few hard-coded dependencies for toolkit on top of that, and display them uniformly.

**Comment by gavv** [comment]
Postponed.
