### ISSUE TITLE
release apk has changed signatures?

### ISSUE THREAD

**Issue by lilydjwg** [roc-streaming/roc-droid#55]
```
adb: failed to install roc-droid-0.0.5.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package org.rocstreaming.rocdroid signatures do not match previously installed version; ignoring!]
```

Is this expected?

**Comment by gavv** [comment]
I don't know the reason, but I also experienced this issue. I just removed old apk before installing new one.

Also, AFAIK currently there is no signing step at all, and APK that is attached to github release is debug APK which is automatically signed using some debug certificates built into android tooling.

Maybe @ortex knows more :)

**Comment by ortex** [comment]
No, nothing to add :)

I guess this could happen until we do https://github.com/roc-streaming/roc-droid/issues/39

**Comment by gavv** [comment]
Maybe it's related to kotlin version bump.

**Comment by ortex** [comment]
#39 fixed. Signature wouldn't be changed anymore
