### ISSUE TITLE
Improvement: make app remember last used receiver address

### ISSUE THREAD

**Issue by Ao1Pointblank** [roc-streaming/roc-droid#69]
the app does not remember the last used address, and resets it to 192.168.0.1 whenever it's closed. android 13

**Comment by githubashutoshsoni** [comment]
Hey, if it's available I'd like to work on this.

**Comment by gavv** [comment]
Welcome, thanks!

**Comment by githubashutoshsoni** [comment]
Great, I've completed this, can you please verify ?
