### ISSUE TITLE
Can't build using OpenJDK 17

### ISSUE THREAD

**Issue by gavv** [roc-streaming/roc-droid#71]
This is the same problem as https://github.com/roc-streaming/roc-java/issues/72. The solution would be also the same - update gradle version.

**Comment by akshaymagar2003** [comment]
Can you assign these issue to me

**Comment by githubashutoshsoni** [comment]
Hey, I would like to take this up? Is this still available?

**Comment by gavv** [comment]
@githubashutoshsoni I guess yes!

See also discussion in https://github.com/roc-streaming/roc-java/issues/72

**Comment by githubashutoshsoni** [comment]
So, got it running locally. 
Will be doing a pull request soon. 

![image](https://github.com/roc-streaming/roc-droid/assets/22251909/c6bce6ba-f3fd-477f-90ce-793809cb2d1f)

**Comment by githubashutoshsoni** [comment]
Can you verify this ? @gavv  ? 

https://github.com/roc-streaming/roc-droid/pull/77
